name: fast-cd

on:
  workflow_run:
    workflows: ["fast-ci"]
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to cloud
        run: |
          echo hell-o world
