name: fast-ci

on:
  push:
    branches:
      - main

jobs:
  # CI
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: Install depencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  # CD
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to cloud
        run: |
          echo hell-o world
